In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [3]:
img = torch.Tensor([1,1,1,0,1,2,8,7,6]).reshape(1,1,3,3)

In [4]:
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, padding=0)


In [5]:
sd = conv.state_dict()

In [6]:
sd

OrderedDict([('weight',
              tensor([[[[ 0.2627, -0.3065],
                        [ 0.3331,  0.1540]]]])),
             ('bias', tensor([0.4383]))])

In [7]:
weights = {'weight': torch.Tensor([1,2,3,4]).reshape(2, 2), 'bias': torch.Tensor([0])}

In [8]:
for k in sd:
    with torch.no_grad():
        sd[k].copy_(weights[k])

In [9]:
conv.state_dict()

OrderedDict([('weight',
              tensor([[[[1., 2.],
                        [3., 4.]]]])),
             ('bias', tensor([0.]))])

In [10]:
output = conv(img)


In [11]:
output


tensor([[[[ 7., 14.],
          [54., 50.]]]], grad_fn=<ConvolutionBackward0>)

In [12]:
conv = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=2,
    stride=2,
    padding=1,
)

In [13]:
sd = conv.state_dict()

In [14]:
sd

OrderedDict([('weight',
              tensor([[[[ 0.1694, -0.1770],
                        [ 0.2783,  0.2055]]]])),
             ('bias', tensor([-0.0822]))])

In [15]:
for k in sd:
    with torch.no_grad():
        sd[k].copy_(weights[k])

In [16]:
output = conv(img)

In [17]:
output

tensor([[[[ 4.,  7.],
          [32., 50.]]]], grad_fn=<ConvolutionBackward0>)

In [18]:
img

tensor([[[[1., 1., 1.],
          [0., 1., 2.],
          [8., 7., 6.]]]])

In [19]:
img = torch.Tensor([1,0,2,3]).reshape(1,1,2,2)

In [20]:
img

tensor([[[[1., 0.],
          [2., 3.]]]])

In [21]:
transconv = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=2)

In [22]:
sd = transconv.state_dict()

In [23]:
sd

OrderedDict([('weight',
              tensor([[[[-0.3283,  0.3627],
                        [ 0.1024,  0.0664]]]])),
             ('bias', tensor([0.4587]))])

In [24]:
weights = {'weight': torch.tensor([2,3,4,5]).reshape(1,1,2,2), 'bias': torch.tensor([0])}

In [25]:
for k in sd:
    with torch.no_grad():
        sd[k].copy_(weights[k])

In [26]:
sd

OrderedDict([('weight',
              tensor([[[[2., 3.],
                        [4., 5.]]]])),
             ('bias', tensor([0.]))])

In [27]:
transoutput = transconv(img)

In [28]:
transoutput

tensor([[[[ 2.,  3.,  0.,  0.],
          [ 4.,  5.,  0.,  0.],
          [ 4.,  6.,  6.,  9.],
          [ 8., 10., 12., 15.]]]], grad_fn=<ConvolutionBackward0>)